








apiVersion: v1
kind: Service
metadata:
  name: traffic-office1-gateway-service
  labels:
    app: traffic-office1-gateway
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: traffic-office1-gateway

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-office1-gateway
  labels:
     app: traffic-office1-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-office1-gateway
  template:
    metadata:
      labels:
        app: traffic-office1-gateway
    spec:
      enableServiceLinks: false
      containers:
        - name: traffic-office1-gateway
          image: goanto/smtc_api_gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: OFFICE
              value: "45.539626,-122.929569"
            - name: DBHOST
              value: "http://db-service:9200"
            - name: STHOST
              value: "http://traffic-office1-storage-service:8080"
            - name: NO_PROXY
              value: "*"
            - name: no_proxy
              value: "*"
          volumeMounts:
            - mountPath: /etc/localtime
              name: timezone
              readOnly: true
      volumes:
        - name: timezone
          hostPath:
            path: /etc/localtime
            type: File
      affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: "vcac-zone"
                    operator: NotIn
                    values:
                      - "yes"

---




