









apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-office1-camera-discovery
  labels:
     app: traffic-office1-camera-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-office1-camera-discovery
  template:
    metadata:
      labels:
        app: traffic-office1-camera-discovery
    spec:
      enableServiceLinks: false
      containers:
        - name: traffic-office1-camera-discovery
          image: goanto/smtc_onvif_discovery:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT_SCAN
              value: "-Pn"
            - name: SIM_HOST
              value: "traffic-office1-cameras-service:17000/traffic-office1-cameras-service:17010/traffic-office1-cameras-service:17020/traffic-office1-cameras-service:17030/traffic-office1-cameras-service:17040/"
            - name: SIM_PREFIX
              value: "cams1o1c"
            - name: OFFICE
              value: "45.539626,-122.929569"
            - name: DBHOST
              value: "http://db-service:9200"
            - name: SERVICE_INTERVAL
              value: "30"
            - name: NO_PROXY
              value: "*"
            - name: no_proxy
              value: "*"
          volumeMounts:
            - mountPath: /etc/localtime
              name: timezone
              readOnly: true
      volumes:
          - name: timezone
            hostPath:
                path: /etc/localtime
                type: File
      affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: "vcac-zone"
                    operator: NotIn
                    values:
                      - "yes"





---




